### PR TITLE
fix(apis):use replication key to increment batches

### PR DESCRIPTION
**Pull request by liebstein**
# Description of change
(write a short description or paste a link to JIRA)

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by cmerrick** [comment]
You did it @liebstein!

Thank you for signing the Singer Contribution License Agreement.

**Comment by asaf-erlich** [comment]
Created a local branch to trigger circle ci to run correctly.

**Comment by asaf-erlich** [comment]
Unfortunately pylint failed :(
```
#!/bin/bash -eo pipefail
source /usr/local/share/virtualenvs/tap-zuora/bin/activate
pylint tap_zuora -d missing-docstring,line-too-long,too-many-locals,too-many-arguments,bad-whitespace,no-else-return,unused-argument
************* Module tap_zuora.apis
tap_zuora/apis.py:303:0: C0304: Final newline missing (missing-final-newline)
tap_zuora/apis.py:125:12: W0612: Unused variable 'bookmark' (unused-variable)

-----------------------------------
Your code has been rated at 9.96/10


Exited with code exit status 20
CircleCI received exit code 20
```

**Comment by asaf-erlich** [comment]
Got the local branch passing pylint, doing integ tests now

**Comment by asaf-erlich** [comment]
Ok the integ tests passed, so we're going to go ahead and release a PR alpha for the client to at least unblock you to use this while we do more testing on our end.

**Comment by asaf-erlich** [comment]
A PR Alpha container was created from this PR's code (after I fixed the pylint issues). The connections for this client should use it from now onwards. Can you fix the pylint issues? And we'll try to get this merged shortly after verification that the issue has been resolved by the PR?

**Comment by luandy64** [comment]
I'm closing this PR because I merged the code change in #48 and released it in `v1.2.0` (via #49). Thank you for working on this @liebstein

**Pull request closed without merging**
